title: Titanium Overcast
permalink: /blog/:year/:month/:day/
email: phil.koelpin@gmail.com
description: Aerospace Structures Blog
github_username:  pkoelpin
highlighter: rouge
theme: null
collections:
  references:
    output: true
    sort_by: title